# Generated by Django 5.2.15 on 2026-06-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("register", "Register"),
                    ("password_reset", "Password Reset"),
                ],
                max_length=20,
            ),
        ),
    ]
